-добавил файлы
Alexey-Girin/homework pull request #22
Opened 2017-05-21 09:51 UTC by Alexey-Girin

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	}
разные стили написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +		return false;
нет фигурных скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	return true;
метод всегда возвращает true

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	return true;
метод всегда возвращает true

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +		{
можно if (elem.isNull()) { ... continue; }, а блок внутри if вытащить в тело цикла, чтобы не делать лишние отступы

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +			if (!checkShowConditions(elem, isIcon)) {
разные стили написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +			else if (elem.tagName() == "arc") {
разные стили написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +		if (!checkCondition(showConditions.at(i).toElement())) {
разные стили написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	}
разные стили написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	if (sign == "=~") {
тут и ниже стиль написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	if (str[0] == '\n')
тут и ниже нет фигурных скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +			x = xnum.toFloat() * current_size_x / first_size_x + mStartX;
не хватает фигурных скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +			y = ynum.toFloat() * current_size_y / first_size_y + mStartY;
не хватает фигурных скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	if (!elem.isNull())
можно обойтись без лишних отступов, если изменить условие в if

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +
лишняя пустая строка

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +				pen.setWidth(1);
нет фигурных скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +				pen.setStyle(Qt::SolidLine);
тут и ниже нет скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +				font.setPixelSize(fontsize.toInt() * current_size_y / first_size_y);
нет скобок

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	if (pw == 0 || ph == 0) { // SUDDENLY!!11
тут и ниже стиль написания скобочек

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +
лишняя строка

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	if (!instance()->mLoadedIcons.contains(id)) {
скобка

2017-05-21 10:38 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.h
> +
лишняя пустая строка

2017-05-23 10:05 UTC, yurii-litvinov requested changes
Хочется ещё замечаний, не только по стилю оформления, но и по общей структуре кода и архитектуре. Например, неужели Вам нравятся огромные методы, делающие что-то непонятное? Или куча загадочных полей и методов в одном классе? Всё это постарайтесь описать тоже.

2017-05-23 12:39 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.h
> +		int j;
Можно обойтись без полей i и j, т.к. они никак не связаны с объектом и используются только в качестве счетчиков для циклов и вспомогательных переменных

2017-05-23 12:39 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.h
> +		QString s2;
"s1" и "s2" странные имена для полей + s2 вообще нигде не используется 
еще, я думаю, что можно обойтись без поля s1

2017-05-23 12:39 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	else if (sign == "=") {
Наверное, тут вместо "=" должен быть "=="

2017-05-23 12:39 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.h
> +		int sep;
sep нигде не используется

2017-05-23 12:39 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +		QString str;
Наверное, тут нужно инициализировать  str

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +}
Не совсем ясно, есть ли какой-нибудь профит от таких методов?

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +			pen.setColor(color);
Кажется, что тут не pen должен быть

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +void SdfRenderer::parsestyle(QDomElement &element)
Как я понял, метод задает стиль(?) для pen, brush, font
Наверное, стоит его разделить на три отдельных метода

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +					while (!(d_cont[j] == ' '))
Можно же !=

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +void SdfRenderer::path_draw(QDomElement &element)
Видимо, метод готовит path к рисованию. Думаю, что общую структуру метода можно было упростить, потому что сейчас почти ничего не понятно + в лесенке if-else-if сплошной копипаст

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.h
> +		QFont font;
Мне кажется, что font актуален только для текста, и как-то не понятно, целесообразно ли создавать этот метод

2017-05-24 19:16 UTC, Alexey-Girin commented on semester_2/CodeReview/sdfRenderer.cpp
> +	if (str[0] == '\n')
Хмм, а какой толк от этого if, если, например, str[0] = '\n' и str[1] = '\n'

2017-05-25 13:07 UTC, yurii-litvinov commented on semester_2/CodeReview/sdfRenderer.cpp
> +	else if (sign == "=") {
Сложно сказать, там какой-то странный язык разбирается, не факт, что автор кода имеет над ним контроль.

2017-05-25 13:09 UTC, yurii-litvinov commented on semester_2/CodeReview/sdfRenderer.cpp
> +		QString str;
В C++ не обязательно, это выражение создаст объект на стеке, вызвав у него конструктор без параметров, и это так для всех классов (а вот элементарные типы, массивы и указатели так себя не ведут, у них нет конструкторов). То есть, внезапно, str будет-таки проинициаллизирована пустой строкой.

2017-05-25 13:11 UTC, yurii-litvinov approved these changes

2017-05-25 13:12 UTC, merged