Homework 3.4
Alexey-Girin/homework pull request #28
Opened 2018-11-16 01:53 UTC by Alexey-Girin

2018-11-18 16:00 UTC, yurii-litvinov requested changes

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +}
Не очень люблю файлы по 600 строчек. Было бы лучше сделать вложенные классы отдельными классами и, если хочется структуры, сложить их в отдельный неймспейс (и отдельную папку в проекте).

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit.Tests/TestingSystemTests.cs
> +            Assert.IsTrue(testsCountInfo.TrueTestCount == TrueTestCount);
Тут лучше Assert.AreEqual, чтобы оно более содержательно ругалось, если тест не прошёл

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestMethodsInTypeExecutionInfo.cs
> +            => string.Compare(Type.Name, (obj as TestMethodsInTypeExecutionInfo).Type.Name);
Надо ещё проверять, что мы сравниваемся с объектом правильного типа, раз тут используется не `IComparable<T>`

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +            string[] assemblyPaths_exe = null;
camelCase, please :)

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                throw new PathErrorException();
Совсем терять информацию о предыдущем исключении нельзя. Есть свойство InnerException и соответствующий конструктор, как раз для ситуации, когда исключение бросается потому, что было брошено другое исключение.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +        /// Выполнение обхода и идентификации открытых методов заданного типа.
Это не совсем правда, этот метод не только обходит сборку и идентифицирует методы, он их реально запускает. Методы выше я бы тоже переименовал, их названия запутывают читателя.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                if (methods.AddMethodByAttribute(attribute, metadata))
Какая-то очень запутанная структура данных. Есть metadata, которая по сути пара из Methods и MethodInfo, тут ещё передаётся Methods methods, который, судя по всему, всегда равен metadata.Methods. При этом вообще класс Metadata (и TestMetadata) используется только в Methods, который и так знает, кто он. Есть подозрение, что тут что-то не нужно. Не берусь утверждать наверняка, но, возможно, удастся избавиться от всего Metadata.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +            public string RunTime { get; set; }
Хранить время как строку необычно.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +        }
Это мне не нравится с точки зрения ООП, не ясно разделение ответственности между классами. Кто хранит результаты тестового запуска, DefaultTestStatus и его потомки? Или TestMetadata? У него же есть время теста и исключение. Кто хранит информацию, необходимую для исполнения теста (и зачем?)? TestMetadata? Methods? Или вообще TestMethodsInTypeExecutionInfo? У него тоже есть экземпляр и тип объекта, который не нужен бы был, если бы это был класс, просто хранящий общую статистику тестовых запусков. 

И почему тогда, раз TestMethodsInTypeExecutionInfo хранит информацию об общей статистике тестового прогона и возращается вызывающему, он не хранит детальной информации о запуске тестов, а вместо этого эта информация печатается сама собой при тестовом прогоне? А если мы хотим лог сохранять в файл, а не на консоль?

В общем, я как человек, который видит этот код впервые, могу утверждать, что на первый взгляд это хаос какой-то :) Надо рефакторить, чётко разграничив ответственности классов --- кто-то собирает информацию о тестовых методах, кто-то хранит, кто-то использует её для запуска тестов и сбора информации о запусках, кто-то хранит её, кто-то потом по ней подсчитывает общую статистику, кто-то печатает результаты.

Кстати, IgnoreTestStatus не является подвидом DefaultTestStatus, судя по коду, поэтому с идейной точки зрения не может быть его наследником.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                var attributType = attribute.GetType();
attribut**e**Type, а то как-то по-немецки :)

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +            public void Execution()
Методы должны называться глаголами

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                    lock (BeforeLocker)
Обычно каждому методу создаётся свой экземпляр объекта, на котором сначала запускаются методы Before, затем сам тестовый метод, затем After. Так несколько тестов не должны синхронизироваться по MethodsExecution, и главное, точно не могут портить друг другу данные экземпляра объекта с тестами.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                    stopwatch.Stop();
stopwatch.Stop можно было делать в finally

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                    metadata.MethodInfo.Invoke(metadata.Methods.InstanceOfType, null);
Желательно выдавать диагностику, если тестовый метод плохой (например, принимает параметры или возвращает результат), для этого его надо проверять перед запуском. Это же касается вспомогательных методов.

2018-11-18 16:00 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                    }
Што? :)

2018-11-18 17:44 UTC, Alexey-Girin commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                    lock (BeforeLocker)
В чем тогда различие между методами Before и BeforeClass, если для конкретного теста они все вместе будут выполняться на соответствующем тесту экземпляре перед выполнением самого теста? С After и AfterClass аналогично

2018-11-21 11:48 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                    lock (BeforeLocker)
BeforeClass выполняется один раз для ВСЕХ тестов в классе. Там обычно настраивается внешнее окружение, которым потом будут пользоваться все экземпляры тестового класса --- например, инициализируется тестовая БД.

2018-11-21 12:26 UTC, yurii-litvinov requested changes
В целом всё ок (по крайней мере, код гораздо понятнее, чем было), но хочется более традиционной семантики BeforeClass и AfterClass. Это, кстати, должны быть статические методы, иначе вызывать их один раз нет смысла.

2018-11-21 12:26 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit.Tests/TestingSystemTests.cs
> +        public void CheckTestingSystemWithWithSeveralTypes()
WithWith, опечатка

2018-11-21 12:26 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/Program.cs
> +            Console.ReadKey();
В консольных утилитах так не принято. Может не быть возможности на что-то нажать, если это часть большого скрипта сборки, исполняющегося в CI

2018-11-21 12:26 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/SupportingClasses/DefaultTestExecutionInfo.cs
> +        }
Хм, это ж `public string Result => (Exception == null).ToString();`

2018-11-21 12:26 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/SupportingClasses/DefaultTestExecutionInfo.cs
> +        /// Возможное исключение.
Свойство с неочевидным назначением. Это исключение, которое было брошено во время теста (тогда почему "возможное"?) или исключение, которое ожидал тест (тогда зачем оно здесь, в результатах?).  Судя по Result, первое, но тогда его стоило бы назвать как-нибудь в духе UnexpectedException и написать в комментарии, что оно не null только тогда, когда оно было брошено во время теста и мы его не ожидали.

2018-11-21 12:26 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                return;
Теоретически можно ещё ругаться, если один метод аннотирован несколькими атрибутами сразу

2018-11-21 12:26 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                ExecuteAuxiliaryMethods(methods.AfterMethods, methods.AfterClassMethods, metadata.MethodInfo,
Мне кажется, вообще не стоит запускать вспомогательные методы, если тест заигнорен. Но не знаю, как делают настоящие библиотеки, может, так тоже можно. Так что это можно не править

2018-11-21 17:18 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2018-11-21 17:18 UTC, yurii-litvinov commented on semester_3/homework_4/MyNUnit/MyNUnit/TestingSystem.cs
> +                var methodException = ExecuteAuxiliaryMethods(auxiliaryMethods, Activator.CreateInstance(type));
Я бы запретил методам BeforeClass и AfterClass быть нестатиками, проверял бы это, и тогда не создавал бы экземпляр объекта (статики можно и без CreateInstance вызывать). Потому что создание экземпляра --- это вызов конструктора, который сам может делать что-то злое.

2018-11-21 17:24 UTC, merged